### ISSUE TITLE
In some circumstances, this line of code may panic

### ISSUE THREAD

**Issue by driftluo** [getsentry/sentry-rust#145]
> This method fails if TLS backend cannot be initialized, or the resolver cannot load the system configuration.

https://github.com/getsentry/sentry-rust/blob/793117740aaec01542fa28b394e1893ffdf52ec8/src/transport.rs#L312

backtrace:
```
main ERROR panic  thread 'main' panicked at 'called Result::unwrap() on an Err value: Error(Url(RelativeUrlWithoutBase))': src/libcore/result.rs:997stack backtrace:
   0: ckb_logger::setup_panic_logger::{{closure}}::h95141ced824b2fab (0x56528cbad80e)
             at util/logger/src/lib.rs:279
   1: rust_panic_with_hook (0x56528ccb2078)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x56528ccb1b11)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x56528ccb19f5)
   4: panic_fmt (0x56528cccb44c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h53e904ebc4d0d8d9 (0x56528c3bfcbd)
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/macros.rs:17
   6: <core::result::Result<T, E>>::unwrap::h75aae8296eb6984b (0x56528c3c1ee0)
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/result.rs:798
      sentry::transport::ReqwestHttpTransport::new_internal::http_client::{{closure}}::h76c09bcc157be0d4
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/transport.rs:307
      <core::option::Option<T>>::unwrap_or_else::hccae0366f2e0dd95
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/option.rs:386
      sentry::transport::ReqwestHttpTransport::new_internal::http_client::hc2a2345d273f5dd6
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/transport.rs:302
      sentry::transport::ReqwestHttpTransport::new_internal::h0ee0b6ee7920e86b
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/transport.rs:163
   7: sentry::transport::ReqwestHttpTransport::new::h4d9367ff25dc0033 (0x56528c3c123b)
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/transport.rs:144
      <sentry::transport::DefaultTransportFactory as sentry::transport::TransportFactory>::create_transport::h46c9f22eeea70438
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/transport.rs:105
   8: sentry::client::Client::with_options::hb2161d123e1deba1 (0x56528c38004a)
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/client.rs:365
   9: <sentry::client::Client as core::convert::From<T>>::from::hd8c6989c04097af1 (0x56528c067a6e)
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/client.rs:244
      <T as core::convert::Into<U>>::into::haab03560b39bbed5
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/convert.rs:501
      sentry::client::init::h5459a6b5d68d83da
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.15.5/src/client.rs:658
  10: 
```

**Comment by rye** [comment]
Just looking at your provided output:

```
main ERROR panic  thread 'main' panicked at 'called Result::unwrap() on an Err value: Error(Url(RelativeUrlWithoutBase))': src/libcore/result.rs:997
```

Would you give a full MWE for reproduction? Otherwise this appears to be operating as intended.

**Comment by driftluo** [comment]
Since this error is not in my local environment, I am actively contacting the bug reproducer, but it seems that he is not responding.

As far as I am concerned, I only know that he will encounter it in the win10 wsl environment(ubuntu subsystem). Which version is specific, I am not sure.

ref: https://talk.nervos.org/t/windows-wsl-0-14-0/2801/3

**Comment by jan-auer** [comment]
This is happening due to a non-absolute or invalid proxy URL that is being set in the options. @driftluo could you please find out which format of proxy is being used for this case?

**Comment by jan-auer** [comment]
Closing due to inactivity, feel free to reopen if this is still an issue.
